# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          The Archived Tale
paginate:       5
baseurl:        ""
url:            "http://localhost:8855"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:         
  name:         The Archived Tale
  url:          http://localhost:8855

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
