---
title: The Archived Tale
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    layout: post
    author: Darcy
  uploads:
    title: Uploads
    output: true
permalink: "/:year-:month-:day/:title.html"
paginate: 5
baseurl: 
url: http://tale.siteleaf.net/
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
author:
  name: The Archived Tale
  url: http://tale.siteleaf.net/
version: 3.4.1
github:
  repo: https://github.com/humanfactors/tale
gems:
- jekyll-paginate
